class php::mod::suhosin (
  $log_syslog = '',
  $log_syslog_facility = '',
  $log_syslog_priority = '',
  $log_sapi = '',
  $log_script = '',
  $log_phpscript = '',
  $log_script_name = '',
  $log_phpscript_name = '',
  $log_phpscript_is_safe = '',
  $log_use_x_forwarded_for = '',
  $executor_max_depth = '',
  $executor_include_max_traversal = '',
  $executor_include_whitelist = '',
  $executor_include_blacklist = '',
  $executor_include_allow_writable_files = '',
  $executor_func_whitelist = '',
  $executor_func_blacklist = '',
  $executor_eval_whitelist = '',
  $executor_eval_blacklist = '',
  $executor_disable_eval = '',
  $executor_disable_emodifier = '',
  $executor_allow_symlink = '',
  $simulation = '',
  $apc_bug_workaround = '',
  $sql_bailout_on_error = '',
  $sql_user_prefix = '',
  $sql_user_postfix = '',
  $multiheader = '',
  $memory_limit = '',
  $session_encrypt = '',
  $session_cryptkey = '',
  $session_cryptua = '',
  $session_cryptdocroot = '',
  $session_cryptraddr = '',
  $session_checkraddr = '',
  $cookie_encrypt = '',
  $cookie_cryptkey = '',
  $cookie_cryptua = '',
  $cookie_cryptdocroot = '',
  $cookie_cryptraddr = '',
  $cookie_checkraddr = '',
  $cookie_cryptlist = '',
  $cookie_plainlist = '',
  $filter_action = '',
  $cookie_max_array_depth = '',
  $cookie_max_array_index_length = '',
  $cookie_max_name_length = '',
  $cookie_max_totalname_length = '',
  $cookie_max_value_length = '',
  $cookie_max_vars = '',
  $cookie_disallow_nul = '',
  $get_max_array_depth = '',
  $get_max_array_index_length = '',
  $get_max_name_length = '',
  $get_max_totalname_length = '',
  $get_max_value_length = '',
  $get_max_vars = '',
  $get_disallow_nul = '',
  $post_max_array_depth = '',
  $post_max_array_index_length = '',
  $post_max_name_length = '',
  $post_max_totalname_length = '',
  $post_max_value_length = '',
  $post_max_vars = '',
  $post_disallow_nul = '',
  $request_max_array_depth = '',
  $request_max_array_index_length = '',
  $request_max_totalname_length = '',
  $request_max_value_length = '',
  $request_max_vars = '',
  $request_max_varname_length = '',
  $request_disallow_nul = '',
  $server_encode = '',
  $server_strip = '',
  $upload_max_uploads = '',
  $upload_disallow_elf = '',
  $upload_disallow_binary = '',
  $upload_remove_binary = '',
  $upload_verification_script = '',
  $session_max_id_length = '',
  $coredump = '',
  $protectkey = '',
  $stealth = '',
  $perdir = ''
) {
  $required = $::operatingsystem ? {
    /(?i-mx:centos|fedora|redhat|scientific)/ => [ 'php-suhosin' ],
  }

  package { $required:
    ensure  => latest,
  }

  file { '/etc/php.d/suhosin.ini':
    ensure  => present,
    owner   => 'root',
    group   => 'root',
    mode    => '0644',
    content => template('php/mod/suhosin.erb'),
  }

}
