nagios_service:
  critical-service:
    active_checks_enabled:        '1'
    passive_checks_enabled:       '1'
    parallelize_check:            '1'
    obsess_over_service:          '1'
    check_freshness:              '0'
    notifications_enabled:        '1'
    event_handler_enabled:        '1'
    flap_detection_enabled:       '1'
    process_perf_data:            '1'
    retain_status_information:    '1'
    retain_nonstatus_information: '1'
    is_volatile:                  '0'
    check_period:                 '24x7'
    max_check_attempts:           '2'
    normal_check_interval:        '1'
    retry_check_interval:         '2'
    contact_groups:               'support-sms'
    notification_options:         'w,u,c,f,r'
    notification_interval:        '60'
    notification_period:          '24x7'
    action_url:                   '/pnp4nagios/index.php/graph?host=$HOSTNAME$&srv=$SERVICEDESC$'
    register:                     '0'
  daily-service:
    active_checks_enabled:        '1'
    passive_checks_enabled:       '1'
    parallelize_check:            '1'
    obsess_over_service:          '1'
    check_freshness:              '0'
    notifications_enabled:        '1'
    event_handler_enabled:        '1'
    flap_detection_enabled:       '1'
    process_perf_data:            '1'
    retain_status_information:    '1'
    retain_nonstatus_information: '1'
    is_volatile:                  '0'
    check_period:                 '24x7'
    max_check_attempts:           '4'
    normal_check_interval:        '1440'
    retry_check_interval:         '480'
    contact_groups:               'support'
    notification_options:		      'w,u,c,f,r'
    notification_interval:        '1440'
    notification_period:          '24x7'
    action_url:                   '/pnp4nagios/index.php/graph?host=$HOSTNAME$&srv=$SERVICEDESC$'
    register:                     '0'